-- MySQL Script generated by MySQL Workbench
-- Fri Feb  9 10:24:17 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema kitchening22_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kitchening22_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kitchening22_db` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema kitchening22_migrate
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kitchening22_migrate
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kitchening22_migrate` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `kitchening22_db` ;

-- -----------------------------------------------------
-- Table `kitchening22_db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchening22_db`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `image` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kitchening22_db`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchening22_db`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(255) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `province` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kitchening22_db`.`restaurants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchening22_db`.`restaurants` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `coverPrice` INT NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  `menu_file` VARCHAR(255) NULL,
  `menu_url` VARCHAR(255) NULL,
  `url_map` VARCHAR(255) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `categoryId` INT NULL,
  `addressId` INT NULL,
  `capacity` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_categories_idx` (`categoryId` ASC) VISIBLE,
  INDEX `fk_users_addresss_idx` (`addressId` ASC) VISIBLE,
  CONSTRAINT `fk_restaurants_categories`
    FOREIGN KEY (`categoryId`)
    REFERENCES `kitchening22_db`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_restaurants_address`
    FOREIGN KEY (`addressId`)
    REFERENCES `kitchening22_db`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kitchening22_db`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchening22_db`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kitchening22_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchening22_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NULL,
  `avatar` VARCHAR(255) NULL,
  `addressId` INT NULL,
  `roleId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_address_idx` (`addressId` ASC) VISIBLE,
  INDEX `fk_users_roles_idx` (`roleId` ASC) VISIBLE,
  CONSTRAINT `fk_users_address`
    FOREIGN KEY (`addressId`)
    REFERENCES `kitchening22_db`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`roleId`)
    REFERENCES `kitchening22_db`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kitchening22_db`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchening22_db`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `file` VARCHAR(255) NULL,
  `restaurantId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_images_restaurants_idx` (`restaurantId` ASC) VISIBLE,
  CONSTRAINT `fk_images_restaurants`
    FOREIGN KEY (`restaurantId`)
    REFERENCES `kitchening22_db`.`restaurants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kitchening22_db`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchening22_db`.`bookings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NULL,
  `restaurantId` INT NULL,
  `date` DATETIME NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bookings_users_idx` (`userId` ASC) VISIBLE,
  INDEX `fk_bookings_restaurants_idx` (`restaurantId` ASC) VISIBLE,
  CONSTRAINT `fk_bookings_users`
    FOREIGN KEY (`userId`)
    REFERENCES `kitchening22_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookings_restaurants`
    FOREIGN KEY (`restaurantId`)
    REFERENCES `kitchening22_db`.`restaurants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kitchening22_db`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchening22_db`.`reviews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `restuarantId` INT NOT NULL,
  `comment` TEXT NOT NULL,
  `rating` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reviews_users_idx` (`userId` ASC) VISIBLE,
  INDEX `fk_reviews_restaurants_idx` (`restuarantId` ASC) VISIBLE,
  CONSTRAINT `fk_reviews_users`
    FOREIGN KEY (`userId`)
    REFERENCES `kitchening22_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reviews_restaurants`
    FOREIGN KEY (`restuarantId`)
    REFERENCES `kitchening22_db`.`restaurants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kitchening22_db`.`methods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchening22_db`.`methods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kitchening22_db`.`statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchening22_db`.`statuses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kitchening22_db`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchening22_db`.`payments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` INT NULL,
  `bookingId` INT NOT NULL,
  `methodId` INT NOT NULL,
  `statusId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_payments_bookins_idx` (`bookingId` ASC) VISIBLE,
  INDEX `fk_payments_methods_idx` (`methodId` ASC) VISIBLE,
  INDEX `fk_payments_methods_idx1` (`statusId` ASC) VISIBLE,
  CONSTRAINT `fk_payments_bookings`
    FOREIGN KEY (`bookingId`)
    REFERENCES `kitchening22_db`.`bookings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payments_methods`
    FOREIGN KEY (`methodId`)
    REFERENCES `kitchening22_db`.`methods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payments_methods`
    FOREIGN KEY (`statusId`)
    REFERENCES `kitchening22_db`.`statuses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `kitchening22_migrate` ;

-- -----------------------------------------------------
-- Table `kitchening22_migrate`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchening22_migrate`.`addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `province` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kitchening22_migrate`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchening22_migrate`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kitchening22_migrate`.`restaurants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchening22_migrate`.`restaurants` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `coverPrice` INT NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `menu_file` VARCHAR(255) NULL DEFAULT NULL,
  `menu_url` VARCHAR(255) NULL DEFAULT NULL,
  `url_map` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `capacity` INT NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `categoryId` INT NULL DEFAULT NULL,
  `addressId` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `categoryId` (`categoryId` ASC) VISIBLE,
  INDEX `addressId` (`addressId` ASC) VISIBLE,
  CONSTRAINT `restaurants_ibfk_1`
    FOREIGN KEY (`categoryId`)
    REFERENCES `kitchening22_migrate`.`categories` (`id`),
  CONSTRAINT `restaurants_ibfk_2`
    FOREIGN KEY (`addressId`)
    REFERENCES `kitchening22_migrate`.`addresses` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kitchening22_migrate`.`sequelizemeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchening22_migrate`.`sequelizemeta` (
  `name` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
